language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ENV[heroku_api_key]
  app: gone-hiking
  run: rails db:migrate
  on:
    branch: main
  skip_cleanup: 'true'
