anguage: ruby
rbenv:
- 1.1.2
addons:
  postgresql: 9.6
cache:
- bundler
script:
- rails db:{create,migrate} RAILS_ENV=test
- rspec
deploy:
  provider: heroku
  api_key:
    secure: ENV[heroku_api_key]
  app: gone-hiking
  run: rails db:migrate
  on:
    branch: main
  skip_cleanup: 'true'
